# Generated by Django 2.0.4 on 2018-04-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='integrantes',
            field=models.ManyToManyField(to='personas.Persona'),
        ),
    ]
