# Generated by Django 2.0.2 on 2018-04-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workitems', '__first__'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDefecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_detecta_defecto', to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaTaskRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=600, null=True)),
                ('tiempo_estimado', models.DecimalField(decimal_places=3, max_digits=6)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En proceso'), (2, 'Calidad'), (3, 'Terminada')], default=0)),
                ('fecha_termino', models.DateField(null=True)),
                ('tipo', models.CharField(choices=[('PLAN', 'PLAN'), ('DESARROLLO', 'DESARROLLO'), ('PRUEBAS', 'PRUEBAS'), ('POSTMORTEM', 'POSTMORTEM')], max_length=50, null=True)),
                ('informacion_defecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.InfoDefecto')),
                ('personas', models.ManyToManyField(through='tasks.PersonaTaskRelacion', to='personas.Persona')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workitems.WorkItem')),
            ],
        ),
        migrations.AddField(
            model_name='personataskrelacion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='infodefecto',
            name='task_asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_origen_defecto', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='infodefecto',
            name='task_encontrado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_encuentra_defecto', to='tasks.Task'),
        ),
    ]
