# Generated by Django 2.0.3 on 2018-03-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workitems', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaTaskRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=600, null=True)),
                ('tiempo_estimado', models.DurationField()),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En proceso'), (2, 'Calidad'), (3, 'Terminada')], default=0)),
                ('defecto', models.BooleanField(default=False)),
                ('personas', models.ManyToManyField(through='tasks.PersonaTaskRelacion', to='personas.Persona')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workitems.WorkItem')),
            ],
        ),
        migrations.AddField(
            model_name='personataskrelacion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
