# Generated by Django 2.0.4 on 2018-04-06 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodefecto',
            name='fecha',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='infodefecto',
            name='tipo',
            field=models.CharField(choices=[('Documentación', 'Documentación'), ('Sintaxis', 'Sintaxis'), ('Interfaz', 'Interfaz'), ('Funcionalidad', 'Funcionalidad'), ('Sistema', 'Sistema'), ('Ambiente', 'Ambiente')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tipo',
            field=models.CharField(choices=[('PLAN', 'PLAN'), ('DISEÑO', 'DISEÑO'), ('DESARROLLO', 'DESARROLLO'), ('PRUEBAS', 'PRUEBAS'), ('POSTMORTEM', 'POSTMORTEM'), ('DEFECTOS', 'DEFECTOS')], max_length=50, null=True),
        ),
    ]
